export const fragrances = [
    "Dior Sauvage",
    "Creed Aventus",
    "Bleu de Chanel",
    "Versace Eros",
    "Acqua di Gio - Giorgio Armani",
    "Baccarat Rouge 540 - Maison Francis Kurkdjian",
    "Santal 33 - Le Labo",
    "Tom Ford Black Orchid",
    "Tobacco Vanille - Tom Ford",
    "Oud Wood - Tom Ford",
    "Spicebomb - Viktor&Rolf",
    "Invictus - Paco Rabanne",
    "1 Million - Paco Rabanne",
    "Le Male - Jean Paul Gaultier",
    "CK One - Calvin Klein",
    "Yves Saint Laurent Y",
    "Terre d'Hermès",
    "Voyage d'Hermès",
    "Green Irish Tweed - Creed",
    "Silver Mountain Water - Creed",
    "Layton - Parfums de Marly",
    "Herod - Parfums de Marly",
    "Pegasus - Parfums de Marly",
    "Jazz Club - Maison Margiela",
    "By the Fireplace - Maison Margiela",
    "Black Saffron - Byredo",
    "Gypsy Water - Byredo",
    "Bal d'Afrique - Byredo",
    "Mojave Ghost - Byredo",
    "Dior Homme Intense",
    "Prada L'Homme",
    "L'Homme Idéal - Guerlain",
    "Ombré Leather - Tom Ford",
    "Explorer - Montblanc",
    "Stronger With You - Emporio Armani",
    "YSL La Nuit de l'Homme",
    "Valentino Uomo Born In Roma",
    "Azzaro Wanted by Night",
    "Spicebomb Extreme - Viktor&Rolf",
    "Acqua di Parma Colonia",
    "Guerlain Habit Rouge",
    "Bentley For Men Intense",
    "Encre Noire - Lalique",
    "Man in Black - Bvlgari",
    "Nuit d'Issey - Issey Miyake",
    "Luna Rossa Carbon - Prada",
    "Gentleman - Givenchy",
    "Ultra Male - Jean Paul Gaultier",
    "D&G The One for Men",
    "Sauvage Elixir - Dior",
    "YSL MYSLF",
    "Prada Luna Rossa Ocean",
    "Armani Code Parfum",
    "Jean Paul Gaultier Le Beau Le Parfum",
    "Valentino Uomo Born In Roma Coral Fantasy",
    "Burberry Hero Eau de Parfum",
    "Gucci Guilty Elixir de Parfum Pour Homme",
    "Paco Rabanne Phantom",
    "Tom Ford Grey Vetiver",
    "Creed Viking",
    "Creed Millésime Impérial",
    "Parfums de Marly Carlisle",
    "Parfums de Marly Sedley",
    "Parfums de Marly Greenley",
    "Maison Margiela Coffee Break",
    "Maison Margiela Sailing Day",
    "Byredo Super Cedar",
    "Diptyque Philosykos",
    "Diptyque Tam Dao",
    "Jo Malone Wood Sage & Sea Salt",
    "Jo Malone Myrrh & Tonka",
    "Kilian Angels' Share",
    "Kilian Apple Brandy on the Rocks",
    "Penhaligon's The Tragedy of Lord George",
    "Penhaligon's Juniper Sling",
    "Amouage Reflection Man",
    "Amouage Interlude Man",
    "Xerjoff Naxos",
    "Xerjoff Alexandria II",
    "Initio Side Effect",
    "Initio Oud for Greatness",
    "Roja Parfums Elysium",
    "Mancera Cedrat Boise",
    "Montale Intense Cafe",
    "Viktor&Rolf Spicebomb Night Vision",
    "Azzaro The Most Wanted Parfum",
    "Dolce & Gabbana Light Blue Forever Pour Homme",
    "Versace Dylan Blue",
    "Chanel Allure Homme Sport Eau Extreme",
    "Hermès H24",
    "Cartier Déclaration",
    "Lalique White",
    "Bvlgari Aqva Pour Homme",
    "Issey Miyake L'Eau d'Issey Pour Homme",
    "Montblanc Legend",
    "Carolina Herrera Bad Boy Extreme",
    "Givenchy Gentleman Society",
    "Narciso Rodriguez For Him Bleu Noir",
    "Rochas Moustache Eau de Parfum",
    "Nishane Hacivat"
];
