export const fragrances = [
    "Dior Sauvage",
    "Creed Aventus",
    "Bleu de Chanel",
    "Versace Eros",
    "Acqua di Gio - Giorgio Armani",
    "Baccarat Rouge 540 - Maison Francis Kurkdjian",
    "Santal 33 - Le Labo",
    "Tom Ford Black Orchid",
    "Tobacco Vanille - Tom Ford",
    "Oud Wood - Tom Ford",
    "Spicebomb - Viktor&Rolf",
    "Invictus - Paco Rabanne",
    "1 Million - Paco Rabanne",
    "Le Male - Jean Paul Gaultier",
    "CK One - Calvin Klein",
    "Yves Saint Laurent Y",
    "Terre d'Hermès",
    "Voyage d'Hermès",
    "Green Irish Tweed - Creed",
    "Silver Mountain Water - Creed",
    "Layton - Parfums de Marly",
    "Herod - Parfums de Marly",
    "Pegasus - Parfums de Marly",
    "Jazz Club - Maison Margiela",
    "By the Fireplace - Maison Margiela",
    "Black Saffron - Byredo",
    "Gypsy Water - Byredo",
    "Bal d'Afrique - Byredo",
    "Mojave Ghost - Byredo",
    "Dior Homme Intense",
    "Prada L'Homme",
    "L'Homme Idéal - Guerlain",
    "Ombré Leather - Tom Ford",
    "Explorer - Montblanc",
    "Stronger With You - Emporio Armani",
    "YSL La Nuit de l'Homme",
    "Valentino Uomo Born In Roma",
    "Azzaro Wanted by Night",
    "Spicebomb Extreme - Viktor&Rolf",
    "Acqua di Parma Colonia",
    "Guerlain Habit Rouge",
    "Bentley For Men Intense",
    "Encre Noire - Lalique",
    "Man in Black - Bvlgari",
    "Nuit d'Issey - Issey Miyake",
    "Luna Rossa Carbon - Prada",
    "Gentleman - Givenchy",
    "Ultra Male - Jean Paul Gaultier",
    "D&G The One for Men",
    "Sauvage Elixir - Dior"
];
